/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[4] = {0, 1, 2, 3};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[17] = {4, 4, 0, 4, 7, 9, 10, 0, 1, 2, 3, 1, 2, 3, 2, 3, 3};
static const casadi_int casadi_s3[17] = {4, 4, 0, 1, 3, 6, 10, 0, 0, 1, 0, 1, 2, 0, 1, 2, 3};
static const casadi_int casadi_s4[15] = {11, 1, 0, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static const casadi_int casadi_s5[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s6[19] = {15, 1, 0, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};

static const casadi_real casadi_c0[16] = {1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.};

/* Drone_ode_expl_vde_adj:(i0[11],i1[11],i2[4],i3[11])->(o0[15]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+11, *w1=w+22, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, *w15=w+56, *w16=w+59, w17, *w18=w+63, *w19=w+66, *w20=w+75, *w21=w+84, *w22=w+117, *w23=w+150, w24, *w25=w+163, *w26=w+167, *w27=w+171, *w28=w+175, *w29=w+179, *w30=w+195, *w31=w+211, *w32=w+255, *w33=w+299, *w34=w+327, *w35=w+371, *w36=w+492, w37, w38, w39, w40, w41, w42, w43, w44, w45, w46, w47, w48, *w49=w+515, w50, w51, w52, w53, w54, w55, w56, *w57=w+643;
  /* #0: @0 = zeros(11x1) */
  casadi_clear(w0, 11);
  /* #1: @1 = zeros(3x7) */
  casadi_clear(w1, 21);
  /* #2: @2 = 1 */
  w2 = 1.;
  /* #3: @3 = input[0][5] */
  w3 = arg[0] ? arg[0][5] : 0;
  /* #4: @4 = input[0][3] */
  w4 = arg[0] ? arg[0][3] : 0;
  /* #5: @5 = sq(@4) */
  w5 = casadi_sq( w4 );
  /* #6: @6 = input[0][4] */
  w6 = arg[0] ? arg[0][4] : 0;
  /* #7: @7 = sq(@6) */
  w7 = casadi_sq( w6 );
  /* #8: @5 = (@5+@7) */
  w5 += w7;
  /* #9: @7 = sq(@3) */
  w7 = casadi_sq( w3 );
  /* #10: @5 = (@5+@7) */
  w5 += w7;
  /* #11: @7 = input[0][6] */
  w7 = arg[0] ? arg[0][6] : 0;
  /* #12: @8 = sq(@7) */
  w8 = casadi_sq( w7 );
  /* #13: @5 = (@5+@8) */
  w5 += w8;
  /* #14: @5 = sqrt(@5) */
  w5 = sqrt( w5 );
  /* #15: @8 = (@3/@5) */
  w8  = (w3/w5);
  /* #16: @9 = sq(@8) */
  w9 = casadi_sq( w8 );
  /* #17: @10 = (@7/@5) */
  w10  = (w7/w5);
  /* #18: @11 = sq(@10) */
  w11 = casadi_sq( w10 );
  /* #19: @9 = (@9+@11) */
  w9 += w11;
  /* #20: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #21: @2 = (@2-@9) */
  w2 -= w9;
  /* #22: @9 = (@6/@5) */
  w9  = (w6/w5);
  /* #23: @11 = (@9*@8) */
  w11  = (w9*w8);
  /* #24: @12 = (@4/@5) */
  w12  = (w4/w5);
  /* #25: @13 = (@12*@10) */
  w13  = (w12*w10);
  /* #26: @11 = (@11-@13) */
  w11 -= w13;
  /* #27: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #28: @13 = (@9*@10) */
  w13  = (w9*w10);
  /* #29: @14 = (@12*@8) */
  w14  = (w12*w8);
  /* #30: @13 = (@13+@14) */
  w13 += w14;
  /* #31: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #32: @15 = horzcat(@2, @11, @13) */
  rr=w15;
  *rr++ = w2;
  *rr++ = w11;
  *rr++ = w13;
  /* #33: @15 = @15' */
  /* #34: @2 = (@9*@8) */
  w2  = (w9*w8);
  /* #35: @11 = (@12*@10) */
  w11  = (w12*w10);
  /* #36: @2 = (@2+@11) */
  w2 += w11;
  /* #37: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #38: @11 = 1 */
  w11 = 1.;
  /* #39: @13 = sq(@9) */
  w13 = casadi_sq( w9 );
  /* #40: @14 = sq(@10) */
  w14 = casadi_sq( w10 );
  /* #41: @13 = (@13+@14) */
  w13 += w14;
  /* #42: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #43: @11 = (@11-@13) */
  w11 -= w13;
  /* #44: @13 = (@8*@10) */
  w13  = (w8*w10);
  /* #45: @14 = (@12*@9) */
  w14  = (w12*w9);
  /* #46: @13 = (@13-@14) */
  w13 -= w14;
  /* #47: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #48: @16 = horzcat(@2, @11, @13) */
  rr=w16;
  *rr++ = w2;
  *rr++ = w11;
  *rr++ = w13;
  /* #49: @16 = @16' */
  /* #50: @2 = (@9*@10) */
  w2  = (w9*w10);
  /* #51: @11 = (@12*@8) */
  w11  = (w12*w8);
  /* #52: @2 = (@2-@11) */
  w2 -= w11;
  /* #53: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #54: @11 = (@8*@10) */
  w11  = (w8*w10);
  /* #55: @13 = (@12*@9) */
  w13  = (w12*w9);
  /* #56: @11 = (@11+@13) */
  w11 += w13;
  /* #57: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #58: @13 = 1 */
  w13 = 1.;
  /* #59: @14 = sq(@9) */
  w14 = casadi_sq( w9 );
  /* #60: @17 = sq(@8) */
  w17 = casadi_sq( w8 );
  /* #61: @14 = (@14+@17) */
  w14 += w17;
  /* #62: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #63: @13 = (@13-@14) */
  w13 -= w14;
  /* #64: @18 = horzcat(@2, @11, @13) */
  rr=w18;
  *rr++ = w2;
  *rr++ = w11;
  *rr++ = w13;
  /* #65: @18 = @18' */
  /* #66: @19 = horzcat(@15, @16, @18) */
  rr=w19;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<3; ++i) *rr++ = *cs++;
  /* #67: @20 = @19' */
  for (i=0, rr=w20, cs=w19; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #68: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #69: @21 = horzcat(@1, @20, @15) */
  rr=w21;
  for (i=0, cs=w1; i<21; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  /* #70: @22 = @21' */
  for (i=0, rr=w22, cs=w21; i<11; ++i) for (j=0; j<3; ++j) rr[i+j*11] = *cs++;
  /* #71: @23 = zeros(4x3) */
  casadi_clear(w23, 12);
  /* #72: @2 = 0.5 */
  w2 = 5.0000000000000000e-01;
  /* #73: @11 = 0 */
  w11 = 0.;
  /* #74: @13 = 0 */
  w13 = 0.;
  /* #75: @14 = 0 */
  w14 = 0.;
  /* #76: @17 = input[0][10] */
  w17 = arg[0] ? arg[0][10] : 0;
  /* #77: @24 = (-@17) */
  w24 = (- w17 );
  /* #78: @25 = horzcat(@11, @13, @14, @24) */
  rr=w25;
  *rr++ = w11;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w24;
  /* #79: @25 = @25' */
  /* #80: @11 = 0 */
  w11 = 0.;
  /* #81: @13 = 0 */
  w13 = 0.;
  /* #82: @14 = 0 */
  w14 = 0.;
  /* #83: @26 = horzcat(@11, @13, @17, @14) */
  rr=w26;
  *rr++ = w11;
  *rr++ = w13;
  *rr++ = w17;
  *rr++ = w14;
  /* #84: @26 = @26' */
  /* #85: @11 = 0 */
  w11 = 0.;
  /* #86: @13 = (-@17) */
  w13 = (- w17 );
  /* #87: @14 = 0 */
  w14 = 0.;
  /* #88: @24 = 0 */
  w24 = 0.;
  /* #89: @27 = horzcat(@11, @13, @14, @24) */
  rr=w27;
  *rr++ = w11;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w24;
  /* #90: @27 = @27' */
  /* #91: @11 = 0 */
  w11 = 0.;
  /* #92: @13 = 0 */
  w13 = 0.;
  /* #93: @14 = 0 */
  w14 = 0.;
  /* #94: @28 = horzcat(@17, @11, @13, @14) */
  rr=w28;
  *rr++ = w17;
  *rr++ = w11;
  *rr++ = w13;
  *rr++ = w14;
  /* #95: @28 = @28' */
  /* #96: @29 = horzcat(@25, @26, @27, @28) */
  rr=w29;
  for (i=0, cs=w25; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<4; ++i) *rr++ = *cs++;
  /* #97: @30 = @29' */
  for (i=0, rr=w30, cs=w29; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #98: @30 = (@2*@30) */
  for (i=0, rr=w30, cs=w30; i<16; ++i) (*rr++)  = (w2*(*cs++));
  /* #99: @29 = zeros(4x4) */
  casadi_clear(w29, 16);
  /* #100: @31 = horzcat(@23, @30, @29) */
  rr=w31;
  for (i=0, cs=w23; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<16; ++i) *rr++ = *cs++;
  /* #101: @32 = @31' */
  for (i=0, rr=w32, cs=w31; i<11; ++i) for (j=0; j<4; ++j) rr[i+j*11] = *cs++;
  /* #102: @33 = zeros(4x7) */
  casadi_clear(w33, 28);
  /* #103: @30 = zeros(4x4) */
  casadi_clear(w30, 16);
  /* #104: @11 = 0.5941 */
  w11 = 5.9409999999999996e-01;
  /* #105: (@30[0] = @11) */
  for (rr=w30+0, ss=(&w11); rr!=w30+1; rr+=1) *rr = *ss++;
  /* #106: @11 = -0.8109 */
  w11 = -8.1089999999999995e-01;
  /* #107: @13 = input[0][7] */
  w13 = arg[0] ? arg[0][7] : 0;
  /* #108: @14 = (@11*@13) */
  w14  = (w11*w13);
  /* #109: (@30[4] = @14) */
  for (rr=w30+4, ss=(&w14); rr!=w30+5; rr+=1) *rr = *ss++;
  /* #110: @14 = 0 */
  w14 = 0.;
  /* #111: (@30[8] = @14) */
  for (rr=w30+8, ss=(&w14); rr!=w30+9; rr+=1) *rr = *ss++;
  /* #112: @14 = 0 */
  w14 = 0.;
  /* #113: (@30[12] = @14) */
  for (rr=w30+12, ss=(&w14); rr!=w30+13; rr+=1) *rr = *ss++;
  /* #114: @14 = 0.3984 */
  w14 = 3.9839999999999998e-01;
  /* #115: @24 = (@14*@13) */
  w24  = (w14*w13);
  /* #116: (@30[1] = @24) */
  for (rr=w30+1, ss=(&w24); rr!=w30+2; rr+=1) *rr = *ss++;
  /* #117: @24 = 0.704 */
  w24 = 7.0399999999999996e-01;
  /* #118: (@30[5] = @24) */
  for (rr=w30+5, ss=(&w24); rr!=w30+6; rr+=1) *rr = *ss++;
  /* #119: @24 = 0 */
  w24 = 0.;
  /* #120: (@30[9] = @24) */
  for (rr=w30+9, ss=(&w24); rr!=w30+10; rr+=1) *rr = *ss++;
  /* #121: @24 = 0 */
  w24 = 0.;
  /* #122: (@30[13] = @24) */
  for (rr=w30+13, ss=(&w24); rr!=w30+14; rr+=1) *rr = *ss++;
  /* #123: @24 = 0 */
  w24 = 0.;
  /* #124: (@30[2] = @24) */
  for (rr=w30+2, ss=(&w24); rr!=w30+3; rr+=1) *rr = *ss++;
  /* #125: @24 = 0 */
  w24 = 0.;
  /* #126: (@30[6] = @24) */
  for (rr=w30+6, ss=(&w24); rr!=w30+7; rr+=1) *rr = *ss++;
  /* #127: @24 = 0.9365 */
  w24 = 9.3650000000000000e-01;
  /* #128: (@30[10] = @24) */
  for (rr=w30+10, ss=(&w24); rr!=w30+11; rr+=1) *rr = *ss++;
  /* #129: @24 = 0 */
  w24 = 0.;
  /* #130: (@30[14] = @24) */
  for (rr=w30+14, ss=(&w24); rr!=w30+15; rr+=1) *rr = *ss++;
  /* #131: @24 = 0 */
  w24 = 0.;
  /* #132: (@30[3] = @24) */
  for (rr=w30+3, ss=(&w24); rr!=w30+4; rr+=1) *rr = *ss++;
  /* #133: @24 = 0 */
  w24 = 0.;
  /* #134: (@30[7] = @24) */
  for (rr=w30+7, ss=(&w24); rr!=w30+8; rr+=1) *rr = *ss++;
  /* #135: @24 = 0 */
  w24 = 0.;
  /* #136: (@30[11] = @24) */
  for (rr=w30+11, ss=(&w24); rr!=w30+12; rr+=1) *rr = *ss++;
  /* #137: @24 = 0.9752 */
  w24 = 9.7519999999999996e-01;
  /* #138: (@30[15] = @24) */
  for (rr=w30+15, ss=(&w24); rr!=w30+16; rr+=1) *rr = *ss++;
  /* #139: @29 = zeros(4x4) */
  casadi_clear(w29, 16);
  /* #140: @24 = 0.6756 */
  w24 = 6.7559999999999998e-01;
  /* #141: (@29[0] = @24) */
  for (rr=w29+0, ss=(&w24); rr!=w29+1; rr+=1) *rr = *ss++;
  /* #142: @24 = 0 */
  w24 = 0.;
  /* #143: (@29[4] = @24) */
  for (rr=w29+4, ss=(&w24); rr!=w29+5; rr+=1) *rr = *ss++;
  /* #144: @24 = 0 */
  w24 = 0.;
  /* #145: (@29[8] = @24) */
  for (rr=w29+8, ss=(&w24); rr!=w29+9; rr+=1) *rr = *ss++;
  /* #146: @24 = 0 */
  w24 = 0.;
  /* #147: (@29[12] = @24) */
  for (rr=w29+12, ss=(&w24); rr!=w29+13; rr+=1) *rr = *ss++;
  /* #148: @24 = 0 */
  w24 = 0.;
  /* #149: (@29[1] = @24) */
  for (rr=w29+1, ss=(&w24); rr!=w29+2; rr+=1) *rr = *ss++;
  /* #150: @24 = 0.6344 */
  w24 = 6.3439999999999996e-01;
  /* #151: (@29[5] = @24) */
  for (rr=w29+5, ss=(&w24); rr!=w29+6; rr+=1) *rr = *ss++;
  /* #152: @24 = 0 */
  w24 = 0.;
  /* #153: (@29[9] = @24) */
  for (rr=w29+9, ss=(&w24); rr!=w29+10; rr+=1) *rr = *ss++;
  /* #154: @24 = 0 */
  w24 = 0.;
  /* #155: (@29[13] = @24) */
  for (rr=w29+13, ss=(&w24); rr!=w29+14; rr+=1) *rr = *ss++;
  /* #156: @24 = 0 */
  w24 = 0.;
  /* #157: (@29[2] = @24) */
  for (rr=w29+2, ss=(&w24); rr!=w29+3; rr+=1) *rr = *ss++;
  /* #158: @24 = 0 */
  w24 = 0.;
  /* #159: (@29[6] = @24) */
  for (rr=w29+6, ss=(&w24); rr!=w29+7; rr+=1) *rr = *ss++;
  /* #160: @24 = 0.408 */
  w24 = 4.0799999999999997e-01;
  /* #161: (@29[10] = @24) */
  for (rr=w29+10, ss=(&w24); rr!=w29+11; rr+=1) *rr = *ss++;
  /* #162: @24 = 0 */
  w24 = 0.;
  /* #163: (@29[14] = @24) */
  for (rr=w29+14, ss=(&w24); rr!=w29+15; rr+=1) *rr = *ss++;
  /* #164: @24 = 0 */
  w24 = 0.;
  /* #165: (@29[3] = @24) */
  for (rr=w29+3, ss=(&w24); rr!=w29+4; rr+=1) *rr = *ss++;
  /* #166: @24 = 0 */
  w24 = 0.;
  /* #167: (@29[7] = @24) */
  for (rr=w29+7, ss=(&w24); rr!=w29+8; rr+=1) *rr = *ss++;
  /* #168: @24 = 0 */
  w24 = 0.;
  /* #169: (@29[11] = @24) */
  for (rr=w29+11, ss=(&w24); rr!=w29+12; rr+=1) *rr = *ss++;
  /* #170: @24 = 0.2953 */
  w24 = 2.9530000000000001e-01;
  /* #171: (@29[15] = @24) */
  for (rr=w29+15, ss=(&w24); rr!=w29+16; rr+=1) *rr = *ss++;
  /* #172: @30 = (@29\@30) */
  rr = w30;
  ss = w29;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[10], r[10], beta[4], w[8];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 4, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #173: @30 = (-@30) */
  for (i=0, rr=w30, cs=w30; i<16; ++i) *rr++ = (- *cs++ );
  /* #174: @31 = horzcat(@33, @30) */
  rr=w31;
  for (i=0, cs=w33; i<28; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<16; ++i) *rr++ = *cs++;
  /* #175: @34 = @31' */
  for (i=0, rr=w34, cs=w31; i<11; ++i) for (j=0; j<4; ++j) rr[i+j*11] = *cs++;
  /* #176: @35 = horzcat(@22, @32, @34) */
  rr=w35;
  for (i=0, cs=w22; i<33; ++i) *rr++ = *cs++;
  for (i=0, cs=w32; i<44; ++i) *rr++ = *cs++;
  for (i=0, cs=w34; i<44; ++i) *rr++ = *cs++;
  /* #177: @36 = input[1][0] */
  casadi_copy(arg[1], 11, w36);
  /* #178: @0 = mac(@35,@36,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, ss=w35+j, tt=w36+i*11; k<11; ++k) *rr += ss[k*11]**tt++;
  /* #179: {@24, @37, @38, @39, @40, @41, @42, @43, @44, @45, @46} = vertsplit(@0) */
  w24 = w0[0];
  w37 = w0[1];
  w38 = w0[2];
  w39 = w0[3];
  w40 = w0[4];
  w41 = w0[5];
  w42 = w0[6];
  w43 = w0[7];
  w44 = w0[8];
  w45 = w0[9];
  w46 = w0[10];
  /* #180: output[0][0] = @24 */
  if (res[0]) res[0][0] = w24;
  /* #181: output[0][1] = @37 */
  if (res[0]) res[0][1] = w37;
  /* #182: output[0][2] = @38 */
  if (res[0]) res[0][2] = w38;
  /* #183: @35 = zeros(11x11) */
  casadi_clear(w35, 121);
  /* #184: @38 = input[0][0] */
  w38 = arg[0] ? arg[0][0] : 0;
  /* #185: @37 = input[0][1] */
  w37 = arg[0] ? arg[0][1] : 0;
  /* #186: @24 = input[0][2] */
  w24 = arg[0] ? arg[0][2] : 0;
  /* #187: @47 = input[0][8] */
  w47 = arg[0] ? arg[0][8] : 0;
  /* #188: @48 = input[0][9] */
  w48 = arg[0] ? arg[0][9] : 0;
  /* #189: @0 = vertcat(@38, @37, @24, @4, @6, @3, @7, @13, @47, @48, @17) */
  rr=w0;
  *rr++ = w38;
  *rr++ = w37;
  *rr++ = w24;
  *rr++ = w4;
  *rr++ = w6;
  *rr++ = w3;
  *rr++ = w7;
  *rr++ = w13;
  *rr++ = w47;
  *rr++ = w48;
  *rr++ = w17;
  /* #190: @0 = @0' */
  /* #191: @35 = mac(@36,@0,@35) */
  for (i=0, rr=w35; i<11; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, ss=w36+j, tt=w0+i*1; k<1; ++k) *rr += ss[k*11]**tt++;
  /* #192: @49 = @35' */
  for (i=0, rr=w49, cs=w35; i<11; ++i) for (j=0; j<11; ++j) rr[i+j*11] = *cs++;
  /* #193: {@22, @32, @34} = horzsplit(@49) */
  casadi_copy(w49, 33, w22);
  casadi_copy(w49+33, 44, w32);
  casadi_copy(w49+77, 44, w34);
  /* #194: @21 = @22' */
  for (i=0, rr=w21, cs=w22; i<3; ++i) for (j=0; j<11; ++j) rr[i+j*3] = *cs++;
  /* #195: {NULL, @20, NULL} = horzsplit(@21) */
  casadi_copy(w21+21, 9, w20);
  /* #196: @19 = @20' */
  for (i=0, rr=w19, cs=w20; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #197: {@15, @16, @18} = horzsplit(@19) */
  casadi_copy(w19, 3, w15);
  casadi_copy(w19+3, 3, w16);
  casadi_copy(w19+6, 3, w18);
  /* #198: @18 = @18' */
  /* #199: {@38, @37, @24} = horzsplit(@18) */
  w38 = w18[0];
  w37 = w18[1];
  w24 = w18[2];
  /* #200: @37 = (2.*@37) */
  w37 = (2.* w37 );
  /* #201: @13 = (@9*@37) */
  w13  = (w9*w37);
  /* #202: @38 = (2.*@38) */
  w38 = (2.* w38 );
  /* #203: @47 = (@8*@38) */
  w47  = (w8*w38);
  /* #204: @13 = (@13-@47) */
  w13 -= w47;
  /* #205: @16 = @16' */
  /* #206: {@47, @48, @17} = horzsplit(@16) */
  w47 = w16[0];
  w48 = w16[1];
  w17 = w16[2];
  /* #207: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #208: @50 = (@9*@17) */
  w50  = (w9*w17);
  /* #209: @13 = (@13-@50) */
  w13 -= w50;
  /* #210: @47 = (2.*@47) */
  w47 = (2.* w47 );
  /* #211: @50 = (@10*@47) */
  w50  = (w10*w47);
  /* #212: @13 = (@13+@50) */
  w13 += w50;
  /* #213: @15 = @15' */
  /* #214: {@50, @51, @52} = horzsplit(@15) */
  w50 = w15[0];
  w51 = w15[1];
  w52 = w15[2];
  /* #215: @52 = (2.*@52) */
  w52 = (2.* w52 );
  /* #216: @53 = (@8*@52) */
  w53  = (w8*w52);
  /* #217: @13 = (@13+@53) */
  w13 += w53;
  /* #218: @51 = (2.*@51) */
  w51 = (2.* w51 );
  /* #219: @53 = (@10*@51) */
  w53  = (w10*w51);
  /* #220: @13 = (@13-@53) */
  w13 -= w53;
  /* #221: @53 = (@13/@5) */
  w53  = (w13/w5);
  /* #222: @39 = (@39+@53) */
  w39 += w53;
  /* #223: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #224: @53 = (@9/@5) */
  w53  = (w9/w5);
  /* #225: @54 = (2.*@9) */
  w54 = (2.* w9 );
  /* #226: @24 = (-@24) */
  w24 = (- w24 );
  /* #227: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #228: @54 = (@54*@24) */
  w54 *= w24;
  /* #229: @55 = (@12*@37) */
  w55  = (w12*w37);
  /* #230: @54 = (@54+@55) */
  w54 += w55;
  /* #231: @55 = (@10*@38) */
  w55  = (w10*w38);
  /* #232: @54 = (@54+@55) */
  w54 += w55;
  /* #233: @55 = (@12*@17) */
  w55  = (w12*w17);
  /* #234: @54 = (@54-@55) */
  w54 -= w55;
  /* #235: @55 = (2.*@9) */
  w55 = (2.* w9 );
  /* #236: @48 = (-@48) */
  w48 = (- w48 );
  /* #237: @48 = (2.*@48) */
  w48 = (2.* w48 );
  /* #238: @55 = (@55*@48) */
  w55 *= w48;
  /* #239: @54 = (@54+@55) */
  w54 += w55;
  /* #240: @55 = (@8*@47) */
  w55  = (w8*w47);
  /* #241: @54 = (@54+@55) */
  w54 += w55;
  /* #242: @55 = (@10*@52) */
  w55  = (w10*w52);
  /* #243: @54 = (@54+@55) */
  w54 += w55;
  /* #244: @55 = (@8*@51) */
  w55  = (w8*w51);
  /* #245: @54 = (@54+@55) */
  w54 += w55;
  /* #246: @53 = (@53*@54) */
  w53 *= w54;
  /* #247: @53 = (-@53) */
  w53 = (- w53 );
  /* #248: @55 = (@12/@5) */
  w55  = (w12/w5);
  /* #249: @55 = (@55*@13) */
  w55 *= w13;
  /* #250: @53 = (@53-@55) */
  w53 -= w55;
  /* #251: @55 = (@10/@5) */
  w55  = (w10/w5);
  /* #252: @13 = (@8*@37) */
  w13  = (w8*w37);
  /* #253: @56 = (@9*@38) */
  w56  = (w9*w38);
  /* #254: @13 = (@13+@56) */
  w13 += w56;
  /* #255: @56 = (@8*@17) */
  w56  = (w8*w17);
  /* #256: @13 = (@13+@56) */
  w13 += w56;
  /* #257: @56 = (2.*@10) */
  w56 = (2.* w10 );
  /* #258: @56 = (@56*@48) */
  w56 *= w48;
  /* #259: @13 = (@13+@56) */
  w13 += w56;
  /* #260: @56 = (@12*@47) */
  w56  = (w12*w47);
  /* #261: @13 = (@13+@56) */
  w13 += w56;
  /* #262: @56 = (@9*@52) */
  w56  = (w9*w52);
  /* #263: @13 = (@13+@56) */
  w13 += w56;
  /* #264: @56 = (@12*@51) */
  w56  = (w12*w51);
  /* #265: @13 = (@13-@56) */
  w13 -= w56;
  /* #266: @56 = (2.*@10) */
  w56 = (2.* w10 );
  /* #267: @50 = (-@50) */
  w50 = (- w50 );
  /* #268: @50 = (2.*@50) */
  w50 = (2.* w50 );
  /* #269: @56 = (@56*@50) */
  w56 *= w50;
  /* #270: @13 = (@13+@56) */
  w13 += w56;
  /* #271: @55 = (@55*@13) */
  w55 *= w13;
  /* #272: @53 = (@53-@55) */
  w53 -= w55;
  /* #273: @55 = (@8/@5) */
  w55  = (w8/w5);
  /* #274: @56 = (2.*@8) */
  w56 = (2.* w8 );
  /* #275: @56 = (@56*@24) */
  w56 *= w24;
  /* #276: @37 = (@10*@37) */
  w37  = (w10*w37);
  /* #277: @56 = (@56+@37) */
  w56 += w37;
  /* #278: @38 = (@12*@38) */
  w38  = (w12*w38);
  /* #279: @56 = (@56-@38) */
  w56 -= w38;
  /* #280: @10 = (@10*@17) */
  w10 *= w17;
  /* #281: @56 = (@56+@10) */
  w56 += w10;
  /* #282: @47 = (@9*@47) */
  w47  = (w9*w47);
  /* #283: @56 = (@56+@47) */
  w56 += w47;
  /* #284: @12 = (@12*@52) */
  w12 *= w52;
  /* #285: @56 = (@56+@12) */
  w56 += w12;
  /* #286: @9 = (@9*@51) */
  w9 *= w51;
  /* #287: @56 = (@56+@9) */
  w56 += w9;
  /* #288: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #289: @8 = (@8*@50) */
  w8 *= w50;
  /* #290: @56 = (@56+@8) */
  w56 += w8;
  /* #291: @55 = (@55*@56) */
  w55 *= w56;
  /* #292: @53 = (@53-@55) */
  w53 -= w55;
  /* #293: @55 = (2.*@5) */
  w55 = (2.* w5 );
  /* #294: @53 = (@53/@55) */
  w53 /= w55;
  /* #295: @4 = (@4*@53) */
  w4 *= w53;
  /* #296: @39 = (@39+@4) */
  w39 += w4;
  /* #297: output[0][3] = @39 */
  if (res[0]) res[0][3] = w39;
  /* #298: @54 = (@54/@5) */
  w54 /= w5;
  /* #299: @40 = (@40+@54) */
  w40 += w54;
  /* #300: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #301: @6 = (@6*@53) */
  w6 *= w53;
  /* #302: @40 = (@40+@6) */
  w40 += w6;
  /* #303: output[0][4] = @40 */
  if (res[0]) res[0][4] = w40;
  /* #304: @56 = (@56/@5) */
  w56 /= w5;
  /* #305: @41 = (@41+@56) */
  w41 += w56;
  /* #306: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #307: @3 = (@3*@53) */
  w3 *= w53;
  /* #308: @41 = (@41+@3) */
  w41 += w3;
  /* #309: output[0][5] = @41 */
  if (res[0]) res[0][5] = w41;
  /* #310: @13 = (@13/@5) */
  w13 /= w5;
  /* #311: @42 = (@42+@13) */
  w42 += w13;
  /* #312: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #313: @7 = (@7*@53) */
  w7 *= w53;
  /* #314: @42 = (@42+@7) */
  w42 += w7;
  /* #315: output[0][6] = @42 */
  if (res[0]) res[0][6] = w42;
  /* #316: @31 = @34' */
  for (i=0, rr=w31, cs=w34; i<4; ++i) for (j=0; j<11; ++j) rr[i+j*4] = *cs++;
  /* #317: {NULL, @30} = horzsplit(@31) */
  casadi_copy(w31+28, 16, w30);
  /* #318: @30 = (-@30) */
  for (i=0, rr=w30, cs=w30; i<16; ++i) *rr++ = (- *cs++ );
  /* #319: @30 = (@29'\@30) */
  rr = w30;
  ss = w29;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[10], r[10], beta[4], w[8];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 4, 1, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #320: @42 = 0 */
  w42 = 0.;
  /* #321: (@30[15] = @42) */
  for (rr=w30+15, ss=(&w42); rr!=w30+16; rr+=1) *rr = *ss++;
  /* #322: @42 = 0 */
  w42 = 0.;
  /* #323: (@30[11] = @42) */
  for (rr=w30+11, ss=(&w42); rr!=w30+12; rr+=1) *rr = *ss++;
  /* #324: @42 = 0 */
  w42 = 0.;
  /* #325: (@30[7] = @42) */
  for (rr=w30+7, ss=(&w42); rr!=w30+8; rr+=1) *rr = *ss++;
  /* #326: @42 = 0 */
  w42 = 0.;
  /* #327: (@30[3] = @42) */
  for (rr=w30+3, ss=(&w42); rr!=w30+4; rr+=1) *rr = *ss++;
  /* #328: @42 = 0 */
  w42 = 0.;
  /* #329: (@30[14] = @42) */
  for (rr=w30+14, ss=(&w42); rr!=w30+15; rr+=1) *rr = *ss++;
  /* #330: @42 = 0 */
  w42 = 0.;
  /* #331: (@30[10] = @42) */
  for (rr=w30+10, ss=(&w42); rr!=w30+11; rr+=1) *rr = *ss++;
  /* #332: @42 = 0 */
  w42 = 0.;
  /* #333: (@30[6] = @42) */
  for (rr=w30+6, ss=(&w42); rr!=w30+7; rr+=1) *rr = *ss++;
  /* #334: @42 = 0 */
  w42 = 0.;
  /* #335: (@30[2] = @42) */
  for (rr=w30+2, ss=(&w42); rr!=w30+3; rr+=1) *rr = *ss++;
  /* #336: @42 = 0 */
  w42 = 0.;
  /* #337: (@30[13] = @42) */
  for (rr=w30+13, ss=(&w42); rr!=w30+14; rr+=1) *rr = *ss++;
  /* #338: @42 = 0 */
  w42 = 0.;
  /* #339: (@30[9] = @42) */
  for (rr=w30+9, ss=(&w42); rr!=w30+10; rr+=1) *rr = *ss++;
  /* #340: @42 = 0 */
  w42 = 0.;
  /* #341: (@30[5] = @42) */
  for (rr=w30+5, ss=(&w42); rr!=w30+6; rr+=1) *rr = *ss++;
  /* #342: @42 = @30[1] */
  for (rr=(&w42), ss=w30+1; ss!=w30+2; ss+=1) *rr++ = *ss;
  /* #343: @14 = (@14*@42) */
  w14 *= w42;
  /* #344: @43 = (@43+@14) */
  w43 += w14;
  /* #345: @14 = 0 */
  w14 = 0.;
  /* #346: (@30[1] = @14) */
  for (rr=w30+1, ss=(&w14); rr!=w30+2; rr+=1) *rr = *ss++;
  /* #347: @14 = 0 */
  w14 = 0.;
  /* #348: (@30[12] = @14) */
  for (rr=w30+12, ss=(&w14); rr!=w30+13; rr+=1) *rr = *ss++;
  /* #349: @14 = 0 */
  w14 = 0.;
  /* #350: (@30[8] = @14) */
  for (rr=w30+8, ss=(&w14); rr!=w30+9; rr+=1) *rr = *ss++;
  /* #351: @14 = @30[4] */
  for (rr=(&w14), ss=w30+4; ss!=w30+5; ss+=1) *rr++ = *ss;
  /* #352: @11 = (@11*@14) */
  w11 *= w14;
  /* #353: @43 = (@43+@11) */
  w43 += w11;
  /* #354: output[0][7] = @43 */
  if (res[0]) res[0][7] = w43;
  /* #355: output[0][8] = @44 */
  if (res[0]) res[0][8] = w44;
  /* #356: output[0][9] = @45 */
  if (res[0]) res[0][9] = w45;
  /* #357: @31 = @32' */
  for (i=0, rr=w31, cs=w32; i<4; ++i) for (j=0; j<11; ++j) rr[i+j*4] = *cs++;
  /* #358: {NULL, @30, NULL} = horzsplit(@31) */
  casadi_copy(w31+12, 16, w30);
  /* #359: @30 = (@2*@30) */
  for (i=0, rr=w30, cs=w30; i<16; ++i) (*rr++)  = (w2*(*cs++));
  /* #360: @57 = @30' */
  for (i=0, rr=w57, cs=w30; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #361: {@25, @26, @27, @28} = horzsplit(@57) */
  casadi_copy(w57, 4, w25);
  casadi_copy(w57+4, 4, w26);
  casadi_copy(w57+8, 4, w27);
  casadi_copy(w57+12, 4, w28);
  /* #362: @28 = @28' */
  /* #363: {@2, NULL, NULL, NULL} = horzsplit(@28) */
  w2 = w28[0];
  /* #364: @46 = (@46+@2) */
  w46 += w2;
  /* #365: @27 = @27' */
  /* #366: {NULL, @2, NULL, NULL} = horzsplit(@27) */
  w2 = w27[1];
  /* #367: @46 = (@46-@2) */
  w46 -= w2;
  /* #368: @26 = @26' */
  /* #369: {NULL, NULL, @2, NULL} = horzsplit(@26) */
  w2 = w26[2];
  /* #370: @46 = (@46+@2) */
  w46 += w2;
  /* #371: @25 = @25' */
  /* #372: {NULL, NULL, NULL, @2} = horzsplit(@25) */
  w2 = w25[3];
  /* #373: @46 = (@46-@2) */
  w46 -= w2;
  /* #374: output[0][10] = @46 */
  if (res[0]) res[0][10] = w46;
  /* #375: @25 = zeros(4x1) */
  casadi_clear(w25, 4);
  /* #376: @33 = zeros(4x7) */
  casadi_clear(w33, 28);
  /* #377: @57 = 
  [[1, 0, 0, 0], 
   [0, 1, 0, 0], 
   [0, 0, 1, 0], 
   [0, 0, 0, 1]] */
  casadi_copy(casadi_c0, 16, w57);
  /* #378: @57 = (@29\@57) */
  rr = w57;
  ss = w29;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[10], r[10], beta[4], w[8];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 4, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #379: @29 = @57' */
  for (i=0, rr=w29, cs=w57; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #380: @31 = horzcat(@33, @29) */
  rr=w31;
  for (i=0, cs=w33; i<28; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<16; ++i) *rr++ = *cs++;
  /* #381: @25 = mac(@31,@36,@25) */
  for (i=0, rr=w25; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w31+j, tt=w36+i*11; k<11; ++k) *rr += ss[k*4]**tt++;
  /* #382: {@46, @2, @45, @44} = vertsplit(@25) */
  w46 = w25[0];
  w2 = w25[1];
  w45 = w25[2];
  w44 = w25[3];
  /* #383: output[0][11] = @46 */
  if (res[0]) res[0][11] = w46;
  /* #384: output[0][12] = @2 */
  if (res[0]) res[0][12] = w2;
  /* #385: output[0][13] = @45 */
  if (res[0]) res[0][13] = w45;
  /* #386: output[0][14] = @44 */
  if (res[0]) res[0][14] = w44;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 15;
  if (sz_res) *sz_res = 12;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 659;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
