/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[4] = {0, 1, 2, 3};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[17] = {4, 4, 0, 4, 7, 9, 10, 0, 1, 2, 3, 1, 2, 3, 2, 3, 3};
static const casadi_int casadi_s3[17] = {4, 4, 0, 1, 3, 6, 10, 0, 0, 1, 0, 1, 2, 0, 1, 2, 3};
static const casadi_int casadi_s4[15] = {11, 1, 0, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static const casadi_int casadi_s5[8] = {4, 1, 0, 4, 0, 1, 2, 3};

static const casadi_real casadi_c0[16] = {1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.};

/* Drone_ode_expl_ode_fun:(i0[11],i1[4],i2[11])->(o0[11]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+11, *w1=w+22, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, *w14=w+55, *w15=w+58, *w16=w+61, *w17=w+64, *w18=w+73, *w19=w+82, *w20=w+115, *w21=w+148, *w22=w+160, *w23=w+164, *w24=w+168, *w25=w+172, *w26=w+176, *w27=w+192, *w28=w+208, *w29=w+252, *w30=w+296, *w31=w+324, *w32=w+368, *w33=w+489, *w34=w+610;
  /* #0: @0 = zeros(11x1) */
  casadi_clear(w0, 11);
  /* #1: @1 = zeros(3x7) */
  casadi_clear(w1, 21);
  /* #2: @2 = 1 */
  w2 = 1.;
  /* #3: @3 = input[0][5] */
  w3 = arg[0] ? arg[0][5] : 0;
  /* #4: @4 = input[0][3] */
  w4 = arg[0] ? arg[0][3] : 0;
  /* #5: @5 = sq(@4) */
  w5 = casadi_sq( w4 );
  /* #6: @6 = input[0][4] */
  w6 = arg[0] ? arg[0][4] : 0;
  /* #7: @7 = sq(@6) */
  w7 = casadi_sq( w6 );
  /* #8: @5 = (@5+@7) */
  w5 += w7;
  /* #9: @7 = sq(@3) */
  w7 = casadi_sq( w3 );
  /* #10: @5 = (@5+@7) */
  w5 += w7;
  /* #11: @7 = input[0][6] */
  w7 = arg[0] ? arg[0][6] : 0;
  /* #12: @8 = sq(@7) */
  w8 = casadi_sq( w7 );
  /* #13: @5 = (@5+@8) */
  w5 += w8;
  /* #14: @5 = sqrt(@5) */
  w5 = sqrt( w5 );
  /* #15: @8 = (@3/@5) */
  w8  = (w3/w5);
  /* #16: @9 = sq(@8) */
  w9 = casadi_sq( w8 );
  /* #17: @10 = (@7/@5) */
  w10  = (w7/w5);
  /* #18: @11 = sq(@10) */
  w11 = casadi_sq( w10 );
  /* #19: @9 = (@9+@11) */
  w9 += w11;
  /* #20: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #21: @2 = (@2-@9) */
  w2 -= w9;
  /* #22: @9 = (@6/@5) */
  w9  = (w6/w5);
  /* #23: @11 = (@9*@8) */
  w11  = (w9*w8);
  /* #24: @5 = (@4/@5) */
  w5  = (w4/w5);
  /* #25: @12 = (@5*@10) */
  w12  = (w5*w10);
  /* #26: @11 = (@11-@12) */
  w11 -= w12;
  /* #27: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #28: @12 = (@9*@10) */
  w12  = (w9*w10);
  /* #29: @13 = (@5*@8) */
  w13  = (w5*w8);
  /* #30: @12 = (@12+@13) */
  w12 += w13;
  /* #31: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #32: @14 = horzcat(@2, @11, @12) */
  rr=w14;
  *rr++ = w2;
  *rr++ = w11;
  *rr++ = w12;
  /* #33: @14 = @14' */
  /* #34: @2 = (@9*@8) */
  w2  = (w9*w8);
  /* #35: @11 = (@5*@10) */
  w11  = (w5*w10);
  /* #36: @2 = (@2+@11) */
  w2 += w11;
  /* #37: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #38: @11 = 1 */
  w11 = 1.;
  /* #39: @12 = sq(@9) */
  w12 = casadi_sq( w9 );
  /* #40: @13 = sq(@10) */
  w13 = casadi_sq( w10 );
  /* #41: @12 = (@12+@13) */
  w12 += w13;
  /* #42: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #43: @11 = (@11-@12) */
  w11 -= w12;
  /* #44: @12 = (@8*@10) */
  w12  = (w8*w10);
  /* #45: @13 = (@5*@9) */
  w13  = (w5*w9);
  /* #46: @12 = (@12-@13) */
  w12 -= w13;
  /* #47: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #48: @15 = horzcat(@2, @11, @12) */
  rr=w15;
  *rr++ = w2;
  *rr++ = w11;
  *rr++ = w12;
  /* #49: @15 = @15' */
  /* #50: @2 = (@9*@10) */
  w2  = (w9*w10);
  /* #51: @11 = (@5*@8) */
  w11  = (w5*w8);
  /* #52: @2 = (@2-@11) */
  w2 -= w11;
  /* #53: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #54: @10 = (@8*@10) */
  w10  = (w8*w10);
  /* #55: @5 = (@5*@9) */
  w5 *= w9;
  /* #56: @10 = (@10+@5) */
  w10 += w5;
  /* #57: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #58: @5 = 1 */
  w5 = 1.;
  /* #59: @9 = sq(@9) */
  w9 = casadi_sq( w9 );
  /* #60: @8 = sq(@8) */
  w8 = casadi_sq( w8 );
  /* #61: @9 = (@9+@8) */
  w9 += w8;
  /* #62: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #63: @5 = (@5-@9) */
  w5 -= w9;
  /* #64: @16 = horzcat(@2, @10, @5) */
  rr=w16;
  *rr++ = w2;
  *rr++ = w10;
  *rr++ = w5;
  /* #65: @16 = @16' */
  /* #66: @17 = horzcat(@14, @15, @16) */
  rr=w17;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<3; ++i) *rr++ = *cs++;
  /* #67: @18 = @17' */
  for (i=0, rr=w18, cs=w17; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #68: @14 = zeros(3x1) */
  casadi_clear(w14, 3);
  /* #69: @19 = horzcat(@1, @18, @14) */
  rr=w19;
  for (i=0, cs=w1; i<21; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  /* #70: @20 = @19' */
  for (i=0, rr=w20, cs=w19; i<11; ++i) for (j=0; j<3; ++j) rr[i+j*11] = *cs++;
  /* #71: @21 = zeros(4x3) */
  casadi_clear(w21, 12);
  /* #72: @2 = 0.5 */
  w2 = 5.0000000000000000e-01;
  /* #73: @10 = 0 */
  w10 = 0.;
  /* #74: @5 = 0 */
  w5 = 0.;
  /* #75: @9 = 0 */
  w9 = 0.;
  /* #76: @8 = input[0][10] */
  w8 = arg[0] ? arg[0][10] : 0;
  /* #77: @11 = (-@8) */
  w11 = (- w8 );
  /* #78: @22 = horzcat(@10, @5, @9, @11) */
  rr=w22;
  *rr++ = w10;
  *rr++ = w5;
  *rr++ = w9;
  *rr++ = w11;
  /* #79: @22 = @22' */
  /* #80: @10 = 0 */
  w10 = 0.;
  /* #81: @5 = 0 */
  w5 = 0.;
  /* #82: @9 = 0 */
  w9 = 0.;
  /* #83: @23 = horzcat(@10, @5, @8, @9) */
  rr=w23;
  *rr++ = w10;
  *rr++ = w5;
  *rr++ = w8;
  *rr++ = w9;
  /* #84: @23 = @23' */
  /* #85: @10 = 0 */
  w10 = 0.;
  /* #86: @5 = (-@8) */
  w5 = (- w8 );
  /* #87: @9 = 0 */
  w9 = 0.;
  /* #88: @11 = 0 */
  w11 = 0.;
  /* #89: @24 = horzcat(@10, @5, @9, @11) */
  rr=w24;
  *rr++ = w10;
  *rr++ = w5;
  *rr++ = w9;
  *rr++ = w11;
  /* #90: @24 = @24' */
  /* #91: @10 = 0 */
  w10 = 0.;
  /* #92: @5 = 0 */
  w5 = 0.;
  /* #93: @9 = 0 */
  w9 = 0.;
  /* #94: @25 = horzcat(@8, @10, @5, @9) */
  rr=w25;
  *rr++ = w8;
  *rr++ = w10;
  *rr++ = w5;
  *rr++ = w9;
  /* #95: @25 = @25' */
  /* #96: @26 = horzcat(@22, @23, @24, @25) */
  rr=w26;
  for (i=0, cs=w22; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<4; ++i) *rr++ = *cs++;
  /* #97: @27 = @26' */
  for (i=0, rr=w27, cs=w26; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #98: @27 = (@2*@27) */
  for (i=0, rr=w27, cs=w27; i<16; ++i) (*rr++)  = (w2*(*cs++));
  /* #99: @26 = zeros(4x4) */
  casadi_clear(w26, 16);
  /* #100: @28 = horzcat(@21, @27, @26) */
  rr=w28;
  for (i=0, cs=w21; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<16; ++i) *rr++ = *cs++;
  /* #101: @29 = @28' */
  for (i=0, rr=w29, cs=w28; i<11; ++i) for (j=0; j<4; ++j) rr[i+j*11] = *cs++;
  /* #102: @30 = zeros(4x7) */
  casadi_clear(w30, 28);
  /* #103: @27 = zeros(4x4) */
  casadi_clear(w27, 16);
  /* #104: @2 = 0.5941 */
  w2 = 5.9409999999999996e-01;
  /* #105: (@27[0] = @2) */
  for (rr=w27+0, ss=(&w2); rr!=w27+1; rr+=1) *rr = *ss++;
  /* #106: @2 = -0.8109 */
  w2 = -8.1089999999999995e-01;
  /* #107: @10 = input[0][7] */
  w10 = arg[0] ? arg[0][7] : 0;
  /* #108: @2 = (@2*@10) */
  w2 *= w10;
  /* #109: (@27[4] = @2) */
  for (rr=w27+4, ss=(&w2); rr!=w27+5; rr+=1) *rr = *ss++;
  /* #110: @2 = 0 */
  w2 = 0.;
  /* #111: (@27[8] = @2) */
  for (rr=w27+8, ss=(&w2); rr!=w27+9; rr+=1) *rr = *ss++;
  /* #112: @2 = 0 */
  w2 = 0.;
  /* #113: (@27[12] = @2) */
  for (rr=w27+12, ss=(&w2); rr!=w27+13; rr+=1) *rr = *ss++;
  /* #114: @2 = 0.3984 */
  w2 = 3.9839999999999998e-01;
  /* #115: @2 = (@2*@10) */
  w2 *= w10;
  /* #116: (@27[1] = @2) */
  for (rr=w27+1, ss=(&w2); rr!=w27+2; rr+=1) *rr = *ss++;
  /* #117: @2 = 0.704 */
  w2 = 7.0399999999999996e-01;
  /* #118: (@27[5] = @2) */
  for (rr=w27+5, ss=(&w2); rr!=w27+6; rr+=1) *rr = *ss++;
  /* #119: @2 = 0 */
  w2 = 0.;
  /* #120: (@27[9] = @2) */
  for (rr=w27+9, ss=(&w2); rr!=w27+10; rr+=1) *rr = *ss++;
  /* #121: @2 = 0 */
  w2 = 0.;
  /* #122: (@27[13] = @2) */
  for (rr=w27+13, ss=(&w2); rr!=w27+14; rr+=1) *rr = *ss++;
  /* #123: @2 = 0 */
  w2 = 0.;
  /* #124: (@27[2] = @2) */
  for (rr=w27+2, ss=(&w2); rr!=w27+3; rr+=1) *rr = *ss++;
  /* #125: @2 = 0 */
  w2 = 0.;
  /* #126: (@27[6] = @2) */
  for (rr=w27+6, ss=(&w2); rr!=w27+7; rr+=1) *rr = *ss++;
  /* #127: @2 = 0.9365 */
  w2 = 9.3650000000000000e-01;
  /* #128: (@27[10] = @2) */
  for (rr=w27+10, ss=(&w2); rr!=w27+11; rr+=1) *rr = *ss++;
  /* #129: @2 = 0 */
  w2 = 0.;
  /* #130: (@27[14] = @2) */
  for (rr=w27+14, ss=(&w2); rr!=w27+15; rr+=1) *rr = *ss++;
  /* #131: @2 = 0 */
  w2 = 0.;
  /* #132: (@27[3] = @2) */
  for (rr=w27+3, ss=(&w2); rr!=w27+4; rr+=1) *rr = *ss++;
  /* #133: @2 = 0 */
  w2 = 0.;
  /* #134: (@27[7] = @2) */
  for (rr=w27+7, ss=(&w2); rr!=w27+8; rr+=1) *rr = *ss++;
  /* #135: @2 = 0 */
  w2 = 0.;
  /* #136: (@27[11] = @2) */
  for (rr=w27+11, ss=(&w2); rr!=w27+12; rr+=1) *rr = *ss++;
  /* #137: @2 = 0.9752 */
  w2 = 9.7519999999999996e-01;
  /* #138: (@27[15] = @2) */
  for (rr=w27+15, ss=(&w2); rr!=w27+16; rr+=1) *rr = *ss++;
  /* #139: @26 = zeros(4x4) */
  casadi_clear(w26, 16);
  /* #140: @2 = 0.6756 */
  w2 = 6.7559999999999998e-01;
  /* #141: (@26[0] = @2) */
  for (rr=w26+0, ss=(&w2); rr!=w26+1; rr+=1) *rr = *ss++;
  /* #142: @2 = 0 */
  w2 = 0.;
  /* #143: (@26[4] = @2) */
  for (rr=w26+4, ss=(&w2); rr!=w26+5; rr+=1) *rr = *ss++;
  /* #144: @2 = 0 */
  w2 = 0.;
  /* #145: (@26[8] = @2) */
  for (rr=w26+8, ss=(&w2); rr!=w26+9; rr+=1) *rr = *ss++;
  /* #146: @2 = 0 */
  w2 = 0.;
  /* #147: (@26[12] = @2) */
  for (rr=w26+12, ss=(&w2); rr!=w26+13; rr+=1) *rr = *ss++;
  /* #148: @2 = 0 */
  w2 = 0.;
  /* #149: (@26[1] = @2) */
  for (rr=w26+1, ss=(&w2); rr!=w26+2; rr+=1) *rr = *ss++;
  /* #150: @2 = 0.6344 */
  w2 = 6.3439999999999996e-01;
  /* #151: (@26[5] = @2) */
  for (rr=w26+5, ss=(&w2); rr!=w26+6; rr+=1) *rr = *ss++;
  /* #152: @2 = 0 */
  w2 = 0.;
  /* #153: (@26[9] = @2) */
  for (rr=w26+9, ss=(&w2); rr!=w26+10; rr+=1) *rr = *ss++;
  /* #154: @2 = 0 */
  w2 = 0.;
  /* #155: (@26[13] = @2) */
  for (rr=w26+13, ss=(&w2); rr!=w26+14; rr+=1) *rr = *ss++;
  /* #156: @2 = 0 */
  w2 = 0.;
  /* #157: (@26[2] = @2) */
  for (rr=w26+2, ss=(&w2); rr!=w26+3; rr+=1) *rr = *ss++;
  /* #158: @2 = 0 */
  w2 = 0.;
  /* #159: (@26[6] = @2) */
  for (rr=w26+6, ss=(&w2); rr!=w26+7; rr+=1) *rr = *ss++;
  /* #160: @2 = 0.408 */
  w2 = 4.0799999999999997e-01;
  /* #161: (@26[10] = @2) */
  for (rr=w26+10, ss=(&w2); rr!=w26+11; rr+=1) *rr = *ss++;
  /* #162: @2 = 0 */
  w2 = 0.;
  /* #163: (@26[14] = @2) */
  for (rr=w26+14, ss=(&w2); rr!=w26+15; rr+=1) *rr = *ss++;
  /* #164: @2 = 0 */
  w2 = 0.;
  /* #165: (@26[3] = @2) */
  for (rr=w26+3, ss=(&w2); rr!=w26+4; rr+=1) *rr = *ss++;
  /* #166: @2 = 0 */
  w2 = 0.;
  /* #167: (@26[7] = @2) */
  for (rr=w26+7, ss=(&w2); rr!=w26+8; rr+=1) *rr = *ss++;
  /* #168: @2 = 0 */
  w2 = 0.;
  /* #169: (@26[11] = @2) */
  for (rr=w26+11, ss=(&w2); rr!=w26+12; rr+=1) *rr = *ss++;
  /* #170: @2 = 0.2953 */
  w2 = 2.9530000000000001e-01;
  /* #171: (@26[15] = @2) */
  for (rr=w26+15, ss=(&w2); rr!=w26+16; rr+=1) *rr = *ss++;
  /* #172: @27 = (@26\@27) */
  rr = w27;
  ss = w26;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[10], r[10], beta[4], w[8];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 4, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #173: @27 = (-@27) */
  for (i=0, rr=w27, cs=w27; i<16; ++i) *rr++ = (- *cs++ );
  /* #174: @28 = horzcat(@30, @27) */
  rr=w28;
  for (i=0, cs=w30; i<28; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<16; ++i) *rr++ = *cs++;
  /* #175: @31 = @28' */
  for (i=0, rr=w31, cs=w28; i<11; ++i) for (j=0; j<4; ++j) rr[i+j*11] = *cs++;
  /* #176: @32 = horzcat(@20, @29, @31) */
  rr=w32;
  for (i=0, cs=w20; i<33; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<44; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<44; ++i) *rr++ = *cs++;
  /* #177: @33 = @32' */
  for (i=0, rr=w33, cs=w32; i<11; ++i) for (j=0; j<11; ++j) rr[i+j*11] = *cs++;
  /* #178: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #179: @5 = input[0][1] */
  w5 = arg[0] ? arg[0][1] : 0;
  /* #180: @9 = input[0][2] */
  w9 = arg[0] ? arg[0][2] : 0;
  /* #181: @11 = input[0][8] */
  w11 = arg[0] ? arg[0][8] : 0;
  /* #182: @12 = input[0][9] */
  w12 = arg[0] ? arg[0][9] : 0;
  /* #183: @34 = vertcat(@2, @5, @9, @4, @6, @3, @7, @10, @11, @12, @8) */
  rr=w34;
  *rr++ = w2;
  *rr++ = w5;
  *rr++ = w9;
  *rr++ = w4;
  *rr++ = w6;
  *rr++ = w3;
  *rr++ = w7;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w8;
  /* #184: @0 = mac(@33,@34,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, ss=w33+j, tt=w34+i*11; k<11; ++k) *rr += ss[k*11]**tt++;
  /* #185: @34 = zeros(11x1) */
  casadi_clear(w34, 11);
  /* #186: @30 = zeros(4x7) */
  casadi_clear(w30, 28);
  /* #187: @27 = 
  [[1, 0, 0, 0], 
   [0, 1, 0, 0], 
   [0, 0, 1, 0], 
   [0, 0, 0, 1]] */
  casadi_copy(casadi_c0, 16, w27);
  /* #188: @27 = (@26\@27) */
  rr = w27;
  ss = w26;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[10], r[10], beta[4], w[8];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 4, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #189: @26 = @27' */
  for (i=0, rr=w26, cs=w27; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #190: @29 = horzcat(@30, @26) */
  rr=w29;
  for (i=0, cs=w30; i<28; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<16; ++i) *rr++ = *cs++;
  /* #191: @31 = @29' */
  for (i=0, rr=w31, cs=w29; i<11; ++i) for (j=0; j<4; ++j) rr[i+j*11] = *cs++;
  /* #192: @2 = input[1][0] */
  w2 = arg[1] ? arg[1][0] : 0;
  /* #193: @5 = input[1][1] */
  w5 = arg[1] ? arg[1][1] : 0;
  /* #194: @9 = input[1][2] */
  w9 = arg[1] ? arg[1][2] : 0;
  /* #195: @4 = input[1][3] */
  w4 = arg[1] ? arg[1][3] : 0;
  /* #196: @22 = vertcat(@2, @5, @9, @4) */
  rr=w22;
  *rr++ = w2;
  *rr++ = w5;
  *rr++ = w9;
  *rr++ = w4;
  /* #197: @34 = mac(@31,@22,@34) */
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, ss=w31+j, tt=w22+i*4; k<4; ++k) *rr += ss[k*11]**tt++;
  /* #198: @0 = (@0+@34) */
  for (i=0, rr=w0, cs=w34; i<11; ++i) (*rr++) += (*cs++);
  /* #199: output[0][0] = @0 */
  casadi_copy(w0, 11, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_expl_ode_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_expl_ode_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_expl_ode_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 621;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
