/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_cost_ext_cost_0_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[11] = {1, 4, 0, 1, 2, 3, 4, 0, 0, 0, 0};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[8] = {1, 4, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s3[9] = {1, 3, 0, 1, 2, 3, 0, 0, 0};
static const casadi_int casadi_s4[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s5[7] = {1, 3, 0, 1, 1, 1, 0};
static const casadi_int casadi_s6[7] = {0, 1, 2, 3, 16, 17, 18};
static const casadi_int casadi_s7[7] = {0, 4, 8, 12, 16, 19, 22};
static const casadi_int casadi_s8[8] = {1, 4, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s9[7] = {1, 3, 0, 0, 1, 1, 0};
static const casadi_int casadi_s10[7] = {4, 5, 6, 7, 19, 20, 21};
static const casadi_int casadi_s11[7] = {1, 5, 9, 13, 17, 20, 23};
static const casadi_int casadi_s12[8] = {1, 4, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s13[7] = {1, 3, 0, 0, 0, 1, 0};
static const casadi_int casadi_s14[7] = {8, 9, 10, 11, 22, 23, 24};
static const casadi_int casadi_s15[7] = {2, 6, 10, 14, 18, 21, 24};
static const casadi_int casadi_s16[8] = {1, 4, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s17[43] = {15, 15, 0, 4, 8, 12, 16, 19, 22, 25, 25, 25, 25, 25, 25, 25, 25, 25, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 6, 4, 5, 6, 4, 5, 6};
static const casadi_int casadi_s18[15] = {11, 1, 0, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static const casadi_int casadi_s19[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s20[3] = {0, 0, 0};
static const casadi_int casadi_s21[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s22[19] = {15, 1, 0, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};
static const casadi_int casadi_s23[18] = {0, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

/* Drone_ode_cost_ext_cost_0_fun_jac_hess:(i0[11],i1[4],i2[],i3[11])->(o0,o1[15],o2[15x15,25nz],o3[],o4[0x15]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real w0, *w1=w+2, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, *w13=w+16, *w14=w+27, *w15=w+30, *w16=w+33, *w17=w+42, *w18=w+46, *w19=w+50, *w20=w+54, *w21=w+70, *w22=w+86, *w23=w+95, *w24=w+120, w28, w29, w30, *w31=w+133, *w32=w+148, *w33=w+155, *w42=w+157;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w3 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w4 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w5 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w6 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w7 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w8 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w9 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12) */
  rr=w13;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  /* #14: @14 = @13[:3] */
  for (rr=w14, ss=w13+0; ss!=w13+3; ss+=1) *rr++ = *ss;
  /* #15: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #16: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #17: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #18: @5 = input[0][3] */
  w5 = arg[0] ? arg[0][3] : 0;
  /* #19: @6 = input[0][4] */
  w6 = arg[0] ? arg[0][4] : 0;
  /* #20: @7 = input[0][5] */
  w7 = arg[0] ? arg[0][5] : 0;
  /* #21: @8 = input[0][6] */
  w8 = arg[0] ? arg[0][6] : 0;
  /* #22: @9 = input[0][7] */
  w9 = arg[0] ? arg[0][7] : 0;
  /* #23: @10 = input[0][8] */
  w10 = arg[0] ? arg[0][8] : 0;
  /* #24: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #25: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #26: @13 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12) */
  rr=w13;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  /* #27: @15 = @13[:3] */
  for (rr=w15, ss=w13+0; ss!=w13+3; ss+=1) *rr++ = *ss;
  /* #28: @14 = (@14-@15) */
  for (i=0, rr=w14, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #29: @15 = @14' */
  casadi_copy(w14, 3, w15);
  /* #30: @16 = zeros(3x3) */
  casadi_clear(w16, 9);
  /* #31: @2 = 1.1 */
  w2 = 1.1000000000000001e+00;
  /* #32: (@16[0] = @2) */
  for (rr=w16+0, ss=(&w2); rr!=w16+1; rr+=1) *rr = *ss++;
  /* #33: @2 = 1.1 */
  w2 = 1.1000000000000001e+00;
  /* #34: (@16[4] = @2) */
  for (rr=w16+4, ss=(&w2); rr!=w16+5; rr+=1) *rr = *ss++;
  /* #35: @2 = 1.1 */
  w2 = 1.1000000000000001e+00;
  /* #36: (@16[8] = @2) */
  for (rr=w16+8, ss=(&w2); rr!=w16+9; rr+=1) *rr = *ss++;
  /* #37: @1 = mac(@15,@16,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w15+j, tt=w16+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #38: @0 = mac(@1,@14,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w14+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #39: @2 = 0 */
  w2 = 0.;
  /* #40: @17 = zeros(1x4) */
  casadi_clear(w17, 4);
  /* #41: @3 = input[1][0] */
  w3 = arg[1] ? arg[1][0] : 0;
  /* #42: @4 = input[1][1] */
  w4 = arg[1] ? arg[1][1] : 0;
  /* #43: @5 = input[1][2] */
  w5 = arg[1] ? arg[1][2] : 0;
  /* #44: @6 = input[1][3] */
  w6 = arg[1] ? arg[1][3] : 0;
  /* #45: @18 = vertcat(@3, @4, @5, @6) */
  rr=w18;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  /* #46: @19 = @18' */
  casadi_copy(w18, 4, w19);
  /* #47: @20 = zeros(4x4) */
  casadi_clear(w20, 16);
  /* #48: @3 = 0.26 */
  w3 = 2.6000000000000001e-01;
  /* #49: (@20[0] = @3) */
  for (rr=w20+0, ss=(&w3); rr!=w20+1; rr+=1) *rr = *ss++;
  /* #50: @3 = 0.26 */
  w3 = 2.6000000000000001e-01;
  /* #51: (@20[5] = @3) */
  for (rr=w20+5, ss=(&w3); rr!=w20+6; rr+=1) *rr = *ss++;
  /* #52: @3 = 0.26 */
  w3 = 2.6000000000000001e-01;
  /* #53: (@20[10] = @3) */
  for (rr=w20+10, ss=(&w3); rr!=w20+11; rr+=1) *rr = *ss++;
  /* #54: @3 = 0.26 */
  w3 = 2.6000000000000001e-01;
  /* #55: (@20[15] = @3) */
  for (rr=w20+15, ss=(&w3); rr!=w20+16; rr+=1) *rr = *ss++;
  /* #56: @17 = mac(@19,@20,@17) */
  for (i=0, rr=w17; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w19+j, tt=w20+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #57: @2 = mac(@17,@18,@2) */
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w17+j, tt=w18+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #58: @0 = (@0+@2) */
  w0 += w2;
  /* #59: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #60: @17 = @17' */
  /* #61: @19 = zeros(1x4) */
  casadi_clear(w19, 4);
  /* #62: @18 = @18' */
  /* #63: @21 = @20' */
  for (i=0, rr=w21, cs=w20; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #64: @19 = mac(@18,@21,@19) */
  for (i=0, rr=w19; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w18+j, tt=w21+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #65: @19 = @19' */
  /* #66: @17 = (@17+@19) */
  for (i=0, rr=w17, cs=w19; i<4; ++i) (*rr++) += (*cs++);
  /* #67: {@0, @2, @3, @4} = vertsplit(@17) */
  w0 = w17[0];
  w2 = w17[1];
  w3 = w17[2];
  w4 = w17[3];
  /* #68: output[1][0] = @0 */
  if (res[1]) res[1][0] = w0;
  /* #69: output[1][1] = @2 */
  if (res[1]) res[1][1] = w2;
  /* #70: output[1][2] = @3 */
  if (res[1]) res[1][2] = w3;
  /* #71: output[1][3] = @4 */
  if (res[1]) res[1][3] = w4;
  /* #72: @13 = zeros(11x1) */
  casadi_clear(w13, 11);
  /* #73: @1 = @1' */
  /* #74: @15 = zeros(1x3) */
  casadi_clear(w15, 3);
  /* #75: @14 = @14' */
  /* #76: @22 = @16' */
  for (i=0, rr=w22, cs=w16; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #77: @15 = mac(@14,@22,@15) */
  for (i=0, rr=w15; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w14+j, tt=w22+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #78: @15 = @15' */
  /* #79: @1 = (@1+@15) */
  for (i=0, rr=w1, cs=w15; i<3; ++i) (*rr++) += (*cs++);
  /* #80: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #81: (@13[:3] += @1) */
  for (rr=w13+0, ss=w1; rr!=w13+3; rr+=1) *rr += *ss++;
  /* #82: {@4, @3, @2, @0, @5, @6, @7, @8, @9, @10, @11} = vertsplit(@13) */
  w4 = w13[0];
  w3 = w13[1];
  w2 = w13[2];
  w0 = w13[3];
  w5 = w13[4];
  w6 = w13[5];
  w7 = w13[6];
  w8 = w13[7];
  w9 = w13[8];
  w10 = w13[9];
  w11 = w13[10];
  /* #83: output[1][4] = @4 */
  if (res[1]) res[1][4] = w4;
  /* #84: output[1][5] = @3 */
  if (res[1]) res[1][5] = w3;
  /* #85: output[1][6] = @2 */
  if (res[1]) res[1][6] = w2;
  /* #86: output[1][7] = @0 */
  if (res[1]) res[1][7] = w0;
  /* #87: output[1][8] = @5 */
  if (res[1]) res[1][8] = w5;
  /* #88: output[1][9] = @6 */
  if (res[1]) res[1][9] = w6;
  /* #89: output[1][10] = @7 */
  if (res[1]) res[1][10] = w7;
  /* #90: output[1][11] = @8 */
  if (res[1]) res[1][11] = w8;
  /* #91: output[1][12] = @9 */
  if (res[1]) res[1][12] = w9;
  /* #92: output[1][13] = @10 */
  if (res[1]) res[1][13] = w10;
  /* #93: output[1][14] = @11 */
  if (res[1]) res[1][14] = w11;
  /* #94: @23 = zeros(15x15,25nz) */
  casadi_clear(w23, 25);
  /* #95: @17 = zeros(1x4) */
  casadi_clear(w17, 4);
  /* #96: @24 = ones(15x1,10nz) */
  casadi_fill(w24, 10, 1.);
  /* #97: {@11, NULL, NULL, NULL, @10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@24) */
  w11 = w24[0];
  w10 = w24[1];
  /* #98: @25 = 00 */
  /* #99: @26 = 00 */
  /* #100: @27 = 00 */
  /* #101: @9 = vertcat(@11, @25, @26, @27) */
  rr=(&w9);
  *rr++ = w11;
  /* #102: @11 = @9' */
  casadi_copy((&w9), 1, (&w11));
  /* #103: @17 = mac(@11,@20,@17) */
  casadi_mtimes((&w11), casadi_s2, w20, casadi_s1, w17, casadi_s0, w, 0);
  /* #104: @17 = @17' */
  /* #105: @19 = zeros(1x4) */
  casadi_clear(w19, 4);
  /* #106: @9 = @9' */
  /* #107: @19 = mac(@9,@21,@19) */
  casadi_mtimes((&w9), casadi_s2, w21, casadi_s1, w19, casadi_s0, w, 0);
  /* #108: @19 = @19' */
  /* #109: @17 = (@17+@19) */
  for (i=0, rr=w17, cs=w19; i<4; ++i) (*rr++) += (*cs++);
  /* #110: {@9, @11, @8, @7} = vertsplit(@17) */
  w9 = w17[0];
  w11 = w17[1];
  w8 = w17[2];
  w7 = w17[3];
  /* #111: @13 = zeros(11x1) */
  casadi_clear(w13, 11);
  /* #112: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #113: @6 = @10[0] */
  for (rr=(&w6), ss=(&w10)+0; ss!=(&w10)+1; ss+=1) *rr++ = *ss;
  /* #114: @6 = (-@6) */
  w6 = (- w6 );
  /* #115: @10 = @6' */
  casadi_copy((&w6), 1, (&w10));
  /* #116: @1 = mac(@10,@16,@1) */
  casadi_mtimes((&w10), casadi_s5, w16, casadi_s4, w1, casadi_s3, w, 0);
  /* #117: @1 = @1' */
  /* #118: @15 = zeros(1x3) */
  casadi_clear(w15, 3);
  /* #119: @6 = @6' */
  /* #120: @15 = mac(@6,@22,@15) */
  casadi_mtimes((&w6), casadi_s5, w22, casadi_s4, w15, casadi_s3, w, 0);
  /* #121: @15 = @15' */
  /* #122: @1 = (@1+@15) */
  for (i=0, rr=w1, cs=w15; i<3; ++i) (*rr++) += (*cs++);
  /* #123: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #124: (@13[:3] += @1) */
  for (rr=w13+0, ss=w1; rr!=w13+3; rr+=1) *rr += *ss++;
  /* #125: {@6, @10, @5, @0, @2, @3, @4, @12, @28, @29, @30} = vertsplit(@13) */
  w6 = w13[0];
  w10 = w13[1];
  w5 = w13[2];
  w0 = w13[3];
  w2 = w13[4];
  w3 = w13[5];
  w4 = w13[6];
  w12 = w13[7];
  w28 = w13[8];
  w29 = w13[9];
  w30 = w13[10];
  /* #126: @31 = vertcat(@9, @11, @8, @7, @6, @10, @5, @0, @2, @3, @4, @12, @28, @29, @30) */
  rr=w31;
  *rr++ = w9;
  *rr++ = w11;
  *rr++ = w8;
  *rr++ = w7;
  *rr++ = w6;
  *rr++ = w10;
  *rr++ = w5;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w12;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  /* #127: @32 = @31[:7] */
  for (rr=w32, ss=w31+0; ss!=w31+7; ss+=1) *rr++ = *ss;
  /* #128: (@23[0, 1, 2, 3, 16, 17, 18] = @32) */
  for (cii=casadi_s6, rr=w23, ss=w32; cii!=casadi_s6+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #129: @32 = @31[:7] */
  for (rr=w32, ss=w31+0; ss!=w31+7; ss+=1) *rr++ = *ss;
  /* #130: (@23[0, 4, 8, 12, 16, 19, 22] = @32) */
  for (cii=casadi_s7, rr=w23, ss=w32; cii!=casadi_s7+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #131: @17 = zeros(1x4) */
  casadi_clear(w17, 4);
  /* #132: @25 = 00 */
  /* #133: @33 = ones(15x1,2nz) */
  casadi_fill(w33, 2, 1.);
  /* #134: {NULL, @9, NULL, NULL, NULL, @11, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@33) */
  w9 = w33[0];
  w11 = w33[1];
  /* #135: @26 = 00 */
  /* #136: @27 = 00 */
  /* #137: @8 = vertcat(@25, @9, @26, @27) */
  rr=(&w8);
  *rr++ = w9;
  /* #138: @9 = @8' */
  casadi_copy((&w8), 1, (&w9));
  /* #139: @17 = mac(@9,@20,@17) */
  casadi_mtimes((&w9), casadi_s8, w20, casadi_s1, w17, casadi_s0, w, 0);
  /* #140: @17 = @17' */
  /* #141: @19 = zeros(1x4) */
  casadi_clear(w19, 4);
  /* #142: @8 = @8' */
  /* #143: @19 = mac(@8,@21,@19) */
  casadi_mtimes((&w8), casadi_s8, w21, casadi_s1, w19, casadi_s0, w, 0);
  /* #144: @19 = @19' */
  /* #145: @17 = (@17+@19) */
  for (i=0, rr=w17, cs=w19; i<4; ++i) (*rr++) += (*cs++);
  /* #146: {@8, @9, @7, @6} = vertsplit(@17) */
  w8 = w17[0];
  w9 = w17[1];
  w7 = w17[2];
  w6 = w17[3];
  /* #147: @13 = zeros(11x1) */
  casadi_clear(w13, 11);
  /* #148: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #149: @10 = @11[0] */
  for (rr=(&w10), ss=(&w11)+0; ss!=(&w11)+1; ss+=1) *rr++ = *ss;
  /* #150: @10 = (-@10) */
  w10 = (- w10 );
  /* #151: @11 = @10' */
  casadi_copy((&w10), 1, (&w11));
  /* #152: @1 = mac(@11,@16,@1) */
  casadi_mtimes((&w11), casadi_s9, w16, casadi_s4, w1, casadi_s3, w, 0);
  /* #153: @1 = @1' */
  /* #154: @15 = zeros(1x3) */
  casadi_clear(w15, 3);
  /* #155: @10 = @10' */
  /* #156: @15 = mac(@10,@22,@15) */
  casadi_mtimes((&w10), casadi_s9, w22, casadi_s4, w15, casadi_s3, w, 0);
  /* #157: @15 = @15' */
  /* #158: @1 = (@1+@15) */
  for (i=0, rr=w1, cs=w15; i<3; ++i) (*rr++) += (*cs++);
  /* #159: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #160: (@13[:3] += @1) */
  for (rr=w13+0, ss=w1; rr!=w13+3; rr+=1) *rr += *ss++;
  /* #161: {@10, @11, @5, @0, @2, @3, @4, @12, @28, @29, @30} = vertsplit(@13) */
  w10 = w13[0];
  w11 = w13[1];
  w5 = w13[2];
  w0 = w13[3];
  w2 = w13[4];
  w3 = w13[5];
  w4 = w13[6];
  w12 = w13[7];
  w28 = w13[8];
  w29 = w13[9];
  w30 = w13[10];
  /* #162: @31 = vertcat(@8, @9, @7, @6, @10, @11, @5, @0, @2, @3, @4, @12, @28, @29, @30) */
  rr=w31;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w7;
  *rr++ = w6;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w5;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w12;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  /* #163: @32 = @31[:7] */
  for (rr=w32, ss=w31+0; ss!=w31+7; ss+=1) *rr++ = *ss;
  /* #164: (@23[4, 5, 6, 7, 19, 20, 21] = @32) */
  for (cii=casadi_s10, rr=w23, ss=w32; cii!=casadi_s10+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #165: @32 = @31[:7] */
  for (rr=w32, ss=w31+0; ss!=w31+7; ss+=1) *rr++ = *ss;
  /* #166: (@23[1, 5, 9, 13, 17, 20, 23] = @32) */
  for (cii=casadi_s11, rr=w23, ss=w32; cii!=casadi_s11+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #167: @17 = zeros(1x4) */
  casadi_clear(w17, 4);
  /* #168: @25 = 00 */
  /* #169: @26 = 00 */
  /* #170: @33 = ones(15x1,2nz) */
  casadi_fill(w33, 2, 1.);
  /* #171: {NULL, NULL, @8, NULL, NULL, NULL, @9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@33) */
  w8 = w33[0];
  w9 = w33[1];
  /* #172: @27 = 00 */
  /* #173: @7 = vertcat(@25, @26, @8, @27) */
  rr=(&w7);
  *rr++ = w8;
  /* #174: @8 = @7' */
  casadi_copy((&w7), 1, (&w8));
  /* #175: @17 = mac(@8,@20,@17) */
  casadi_mtimes((&w8), casadi_s12, w20, casadi_s1, w17, casadi_s0, w, 0);
  /* #176: @17 = @17' */
  /* #177: @19 = zeros(1x4) */
  casadi_clear(w19, 4);
  /* #178: @7 = @7' */
  /* #179: @19 = mac(@7,@21,@19) */
  casadi_mtimes((&w7), casadi_s12, w21, casadi_s1, w19, casadi_s0, w, 0);
  /* #180: @19 = @19' */
  /* #181: @17 = (@17+@19) */
  for (i=0, rr=w17, cs=w19; i<4; ++i) (*rr++) += (*cs++);
  /* #182: {@7, @8, @6, @10} = vertsplit(@17) */
  w7 = w17[0];
  w8 = w17[1];
  w6 = w17[2];
  w10 = w17[3];
  /* #183: @13 = zeros(11x1) */
  casadi_clear(w13, 11);
  /* #184: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #185: @11 = @9[0] */
  for (rr=(&w11), ss=(&w9)+0; ss!=(&w9)+1; ss+=1) *rr++ = *ss;
  /* #186: @11 = (-@11) */
  w11 = (- w11 );
  /* #187: @9 = @11' */
  casadi_copy((&w11), 1, (&w9));
  /* #188: @1 = mac(@9,@16,@1) */
  casadi_mtimes((&w9), casadi_s13, w16, casadi_s4, w1, casadi_s3, w, 0);
  /* #189: @1 = @1' */
  /* #190: @15 = zeros(1x3) */
  casadi_clear(w15, 3);
  /* #191: @11 = @11' */
  /* #192: @15 = mac(@11,@22,@15) */
  casadi_mtimes((&w11), casadi_s13, w22, casadi_s4, w15, casadi_s3, w, 0);
  /* #193: @15 = @15' */
  /* #194: @1 = (@1+@15) */
  for (i=0, rr=w1, cs=w15; i<3; ++i) (*rr++) += (*cs++);
  /* #195: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #196: (@13[:3] += @1) */
  for (rr=w13+0, ss=w1; rr!=w13+3; rr+=1) *rr += *ss++;
  /* #197: {@11, @9, @5, @0, @2, @3, @4, @12, @28, @29, @30} = vertsplit(@13) */
  w11 = w13[0];
  w9 = w13[1];
  w5 = w13[2];
  w0 = w13[3];
  w2 = w13[4];
  w3 = w13[5];
  w4 = w13[6];
  w12 = w13[7];
  w28 = w13[8];
  w29 = w13[9];
  w30 = w13[10];
  /* #198: @31 = vertcat(@7, @8, @6, @10, @11, @9, @5, @0, @2, @3, @4, @12, @28, @29, @30) */
  rr=w31;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w6;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w9;
  *rr++ = w5;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w12;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  /* #199: @32 = @31[:7] */
  for (rr=w32, ss=w31+0; ss!=w31+7; ss+=1) *rr++ = *ss;
  /* #200: (@23[8, 9, 10, 11, 22, 23, 24] = @32) */
  for (cii=casadi_s14, rr=w23, ss=w32; cii!=casadi_s14+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #201: @32 = @31[:7] */
  for (rr=w32, ss=w31+0; ss!=w31+7; ss+=1) *rr++ = *ss;
  /* #202: (@23[2, 6, 10, 14, 18, 21, 24] = @32) */
  for (cii=casadi_s15, rr=w23, ss=w32; cii!=casadi_s15+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #203: @17 = zeros(1x4) */
  casadi_clear(w17, 4);
  /* #204: @25 = 00 */
  /* #205: @26 = 00 */
  /* #206: @27 = 00 */
  /* #207: @7 = ones(15x1,1nz) */
  w7 = 1.;
  /* #208: {NULL, NULL, NULL, @8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@7) */
  w8 = w7;
  /* #209: @7 = vertcat(@25, @26, @27, @8) */
  rr=(&w7);
  *rr++ = w8;
  /* #210: @8 = @7' */
  casadi_copy((&w7), 1, (&w8));
  /* #211: @17 = mac(@8,@20,@17) */
  casadi_mtimes((&w8), casadi_s16, w20, casadi_s1, w17, casadi_s0, w, 0);
  /* #212: @17 = @17' */
  /* #213: @19 = zeros(1x4) */
  casadi_clear(w19, 4);
  /* #214: @7 = @7' */
  /* #215: @19 = mac(@7,@21,@19) */
  casadi_mtimes((&w7), casadi_s16, w21, casadi_s1, w19, casadi_s0, w, 0);
  /* #216: @19 = @19' */
  /* #217: @17 = (@17+@19) */
  for (i=0, rr=w17, cs=w19; i<4; ++i) (*rr++) += (*cs++);
  /* #218: {@7, @8, @6, @10} = vertsplit(@17) */
  w7 = w17[0];
  w8 = w17[1];
  w6 = w17[2];
  w10 = w17[3];
  /* #219: @25 = 00 */
  /* #220: @26 = 00 */
  /* #221: @27 = 00 */
  /* #222: @34 = 00 */
  /* #223: @35 = 00 */
  /* #224: @36 = 00 */
  /* #225: @37 = 00 */
  /* #226: @38 = 00 */
  /* #227: @39 = 00 */
  /* #228: @40 = 00 */
  /* #229: @41 = 00 */
  /* #230: @17 = vertcat(@7, @8, @6, @10, @25, @26, @27, @34, @35, @36, @37, @38, @39, @40, @41) */
  rr=w17;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w6;
  *rr++ = w10;
  /* #231: @19 = @17[:4] */
  for (rr=w19, ss=w17+0; ss!=w17+4; ss+=1) *rr++ = *ss;
  /* #232: (@23[12:16] = @19) */
  for (rr=w23+12, ss=w19; rr!=w23+16; rr+=1) *rr = *ss++;
  /* #233: @19 = @17[:4] */
  for (rr=w19, ss=w17+0; ss!=w17+4; ss+=1) *rr++ = *ss;
  /* #234: (@23[3:19:4] = @19) */
  for (rr=w23+3, ss=w19; rr!=w23+19; rr+=4) *rr = *ss++;
  /* #235: @42 = @23' */
  casadi_trans(w23,casadi_s17, w42, casadi_s17, iw);
  /* #236: output[2][0] = @42 */
  casadi_copy(w42, 25, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_0_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_0_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_0_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_0_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_0_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_0_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_cost_ext_cost_0_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_0_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_0_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_0_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s18;
    case 1: return casadi_s19;
    case 2: return casadi_s20;
    case 3: return casadi_s18;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_0_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s21;
    case 1: return casadi_s22;
    case 2: return casadi_s17;
    case 3: return casadi_s20;
    case 4: return casadi_s23;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19;
  if (sz_res) *sz_res = 20;
  if (sz_iw) *sz_iw = 16;
  if (sz_w) *sz_w = 182;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
